### ISSUE TITLE
INTERVAL_MIN is a string

### ISSUE THREAD

**Issue by sebgoa** [u-ichi/fluent-plugin-cloudstack#1]
Hi, you might want to look at:
https://github.com/u-ichi/fluent-plugin-cloudstack/blob/master/lib/fluent/plugin/in_cloudstack.rb#L37

and add a .to_s to INTERVAL_MIN

Also the default of 300 is quite high for debugging, maybe bring it down to 5 ?

**Comment by u-ichi** [comment]
> https://github.com/u-ichi/fluent-plugin-cloudstack/blob/master/lib/fluent/plugin/in_cloudstack.rb#L37
> and add a .to_s to INTERVAL_MIN

oh. it is bug.

> Also the default of 300 is quite high for debugging, maybe bring it down to 5 ?

I think so too, I would like to create debug mode. 
Please wait several days.

**Comment by u-ichi** [comment]
https://github.com/u-ichi/fluent-plugin-cloudstack/commit/3c867faed9245248b766a51fd208bd1b8a4b097f

fixed bug and added debug_mode.
